[package]
name = "relay-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "relay_kernel"
path = "src/lib.rs"
test = true

[[bin]]
name = "relay-kernel"
path = "src/main.rs"
test = false

[dependencies]
boot-info.workspace = true
term.workspace = true
shell.workspace = true
vfs.workspace = true
ext2.workspace = true
usb.workspace = true
x86_64.workspace = true
spin.workspace = true
