//! `cargo xtask gen-font <spleen-8x16.bdf>`: converts the Spleen BDF font into
//! `crates/term/src/font.rs`, a 256-entry table indexed by Latin-1 code.

use anyhow::{Context, Result, bail};
use std::fmt::Write as _;
use std::path::Path;

pub const GLYPH_W: usize = 8;
pub const GLYPH_H: usize = 16;
/// Row of the baseline counted from the top (FONTBOUNDINGBOX 8 16 0 -4).
const BASELINE: i32 = 12;

/// Parses a BDF file into glyph bitmaps for code points 0-255.
/// Missing glyphs are `None`.
pub fn parse_bdf(text: &str) -> Result<Vec<Option<[u8; GLYPH_H]>>> {
    let mut glyphs = vec![None; 256];
    let mut lines = text.lines();
    while let Some(line) = lines.next() {
        if !line.starts_with("STARTCHAR") {
            continue;
        }
        let mut encoding: Option<i64> = None;
        let mut bbx = (GLYPH_W as i32, GLYPH_H as i32, 0, -4);
        let mut rows = Vec::new();
        let mut in_bitmap = false;
        for line in lines.by_ref() {
            let mut parts = line.split_whitespace();
            match parts.next() {
                Some("ENCODING") => encoding = parts.next().map(str::parse).transpose()?,
                Some("BBX") => {
                    let v: Vec<i32> = parts.map(str::parse).collect::<Result<_, _>>()?;
                    if v.len() != 4 {
                        bail!("bad BBX line: {line}");
                    }
                    bbx = (v[0], v[1], v[2], v[3]);
                }
                Some("BITMAP") => in_bitmap = true,
                Some("ENDCHAR") => break,
                Some(hex) if in_bitmap => rows.push(
                    u8::from_str_radix(hex, 16).with_context(|| format!("bad bitmap row {hex}"))?,
                ),
                _ => {}
            }
        }
        let Some(code) = encoding.filter(|c| (0..256).contains(c)) else {
            continue;
        };
        let (w, h, xoff, yoff) = bbx;
        if w + xoff > GLYPH_W as i32 || xoff < 0 {
            bail!("glyph {code} is wider than {GLYPH_W} px");
        }
        let top = BASELINE - (yoff + h);
        let mut glyph = [0u8; GLYPH_H];
        for (i, bits) in rows.iter().enumerate() {
            let y = top + i as i32;
            if (0..GLYPH_H as i32).contains(&y) {
                glyph[y as usize] = bits >> xoff;
            }
        }
        glyphs[code as usize] = Some(glyph);
    }
    Ok(glyphs)
}

/// Renders the Rust source for `crates/term/src/font.rs`.
pub fn render_rust(glyphs: &[Option<[u8; GLYPH_H]>]) -> Result<String> {
    let fallback = glyphs[b'?' as usize].context("font has no '?' glyph")?;
    let mut s = String::new();
    s.push_str("// @generated by `cargo xtask gen-font` from Spleen 8x16 2.1.0.\n");
    s.push_str("// Spleen is Copyright (c) 2018-2024 Frederic Cambus, BSD-2-Clause;\n");
    s.push_str("// see crates/term/fonts/LICENSE. Do not edit by hand.\n\n");
    writeln!(s, "pub const GLYPH_W: usize = {GLYPH_W};")?;
    writeln!(s, "pub const GLYPH_H: usize = {GLYPH_H};\n")?;
    s.push_str("/// Glyph bitmaps indexed by Latin-1 code; one byte per row, MSB = left.\n");
    s.push_str("/// Codes without a glyph use the '?' bitmap.\n");
    writeln!(s, "pub static GLYPHS: [[u8; GLYPH_H]; 256] = [")?;
    for (code, g) in glyphs.iter().enumerate() {
        let g = g.unwrap_or(fallback);
        let bytes: Vec<String> = g.iter().map(|b| format!("0x{b:02X}")).collect();
        writeln!(s, "    [{}], // {code:#04X}", bytes.join(", "))?;
    }
    s.push_str("];\n");
    Ok(s)
}

pub fn gen_font(bdf: &Path) -> Result<()> {
    let text =
        std::fs::read_to_string(bdf).with_context(|| format!("reading {}", bdf.display()))?;
    let glyphs = parse_bdf(&text)?;
    let missing: Vec<usize> = (0x20..=0x7E)
        .chain(0xA0..=0xFF)
        .filter(|&c| glyphs[c].is_none())
        .collect();
    if !missing.is_empty() {
        bail!("font is missing printable Latin-1 glyphs: {missing:X?}");
    }
    let out = crate::util::root().join("crates/term/src/font.rs");
    std::fs::write(&out, render_rust(&glyphs)?)?;
    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&out)
        .status()
        .context("running rustfmt")?;
    anyhow::ensure!(status.success(), "rustfmt failed on {}", out.display());
    println!("wrote {}", out.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "STARTFONT 2.1\nFONTBOUNDINGBOX 8 16 0 -4\n\
STARTCHAR A\nENCODING 65\nBBX 8 16 0 -4\nBITMAP\n\
00\n00\n7C\nC6\nC6\nC6\nFE\nC6\nC6\nC6\nC6\nC6\n00\n00\n00\n00\nENDCHAR\n\
STARTCHAR question\nENCODING 63\nBBX 8 16 0 -4\nBITMAP\n\
00\n00\n7C\nC6\n06\n0C\n18\n18\n00\n18\n18\n00\n00\n00\n00\n00\nENDCHAR\n\
STARTCHAR dot\nENCODING 46\nBBX 2 2 3 0\nBITMAP\nC0\nC0\nENDCHAR\n\
STARTCHAR big\nENCODING 9731\nBBX 8 16 0 -4\nBITMAP\nFF\nENDCHAR\nENDFONT\n";

    #[test]
    fn parses_full_height_glyph() {
        let g = parse_bdf(SAMPLE).unwrap();
        assert_eq!(g[65].unwrap()[2], 0x7C);
        assert_eq!(g[65].unwrap()[6], 0xFE);
    }

    #[test]
    fn places_small_glyph_on_baseline_with_x_offset() {
        let g = parse_bdf(SAMPLE).unwrap()[46].unwrap();
        // BBX 2x2 at yoff 0: rows 10 and 11 (just above the baseline at 12).
        assert_eq!(g[10], 0xC0 >> 3);
        assert_eq!(g[11], 0xC0 >> 3);
        assert_eq!(g[9], 0);
    }

    #[test]
    fn ignores_code_points_above_255() {
        let g = parse_bdf(SAMPLE).unwrap();
        assert_eq!(g.len(), 256);
    }

    #[test]
    fn missing_glyphs_fall_back_to_question_mark() {
        let g = parse_bdf(SAMPLE).unwrap();
        let src = render_rust(&g).unwrap();
        assert!(src.contains("pub static GLYPHS: [[u8; GLYPH_H]; 256]"));
        let line_0 = src.lines().find(|l| l.ends_with("// 0x00")).unwrap();
        let line_q = src.lines().find(|l| l.ends_with("// 0x3F")).unwrap();
        assert_eq!(line_0.split("//").next(), line_q.split("//").next());
    }
}
